/* Automatically generated by './build/bin/build-entry.js' */

import c from '../packages/c.vue';
import e from '../packages/e.vue';
import kv from '../packages/kv.vue';
import my_list from '../packages/my-list.vue';
import my_ref from '../packages/my-ref.vue';

// import Upload1 from '../packages/upload1.vue';
import upload from '../packages/upload.vue';
import my_city from '../packages/my-city.vue';
import number_input from '../packages/number-input.vue';
import number_range from '../packages/number-range.vue';

import image_edit from '../packages/image-edit.vue';


const components = [
  c, e,
  kv,
  my_list, my_ref,
  // Upload1,
  upload,
  my_city,
  number_input,number_range,
  image_edit
];

var components_export = {};

const install = function (Vue, opts = {}) {
  components.map(component => {
    components_export[component.name] = component;
    Vue.component(component.name, component);
  });


  const ELEMENT = {};
  ELEMENT.size = opts.size || '';
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

// components_export["jv"] = jv;
components_export["install"] = install;
module.exports = components_export;
module.exports.default = module.exports;
