/* Automatically generated by './build/bin/build-entry.js' */


import dataType from '../packages/data-type';
import paramList from '../packages/param-list';
import "./base.scss"

const components = [
    dataType, paramList
];

const install = function (Vue, opts = {}) {
    components.forEach(component => {
        // components_export[component.name] = component;
        Vue.component(component.name, component);
    });
};

if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}


import packageJson from "../package.json"

var ret = {
    version: packageJson.version,
    install
};

components.forEach(it => {
    ret[it.name] = it;
})
export default ret;



