/* Automatically generated by './build/bin/build-entry.js' */

import c from '../packages/c.vue';

import "./base.scss"

const components = [
    c
];

const install = function (Vue, opts = {}) {
    components.forEach(component => {
        // components_export[component.name] = component;
        Vue.component(component.name, component);
    });

    menu.install(Vue);
};

if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}


export default install


